name: publish
on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: cache deps
        id: cache-deps
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}-${{ hashFiles('**/*.dhall') }}
          path: |
            node_modules
            .spago
            output
      - name: node setup
        uses: actions/setup-node@v2
      - if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npm install
      - name: build
        run: npm run bundle
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
